require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - vendor/bundle/**/*
    - node_modules/**/*
    - db/schema.rb
    - bin/*
    - lib/tasks/*
    - db/migrate/*
    - config/initializers/moodle_database_loader.rb

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - spec/**/*.rb

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/**/*.rb

Rails:
  Enabled: true

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 12

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false